### ISSUE TITLE
go代码块显示有问题，别的测试了python正常

### ISSUE THREAD

**Issue by Aidanwangcy** [imhanjie/gridea-theme-pure#1]
<img width="207" alt="截屏2020-01-1317 17 49" src="https://user-images.githubusercontent.com/29744854/72244223-c4688f80-3628-11ea-8bde-891129eb164f.png">

**Comment by imhanjie** [comment]
已经修复，安装最新的 1.0.1 试试。

**Comment by Aidanwangcy** [comment]
感谢
