### ISSUE TITLE
无法找到GA配置的地点

### ISSUE THREAD

**Issue by WoadZS** [imhanjie/gridea-theme-pure#13]
在Mac Gridea 0.9.2版本中使用无法找到本主题v1.0.5中配置谷歌分析GA的UA码配置地点，模板文件中只看见header.ejs有相关代码，请问大佬能在什么地方配置GA的UA码？

非常感谢！

**Comment by WoadZS** [comment]
自己通过替换head.ejs的代码搞定了，但还是希望能提供一个配置的入口……因为没有入口看起来像是一个bug

**Comment by imhanjie** [comment]
之前的 GA 配置选项忘记添加了，试试 1.0.6 版本有没有问题。

**Comment by WoadZS** [comment]
验证过了，没问题，辛苦大佬！
