### ISSUE TITLE
为什么我保存完主题，渲染出来是混乱的呢？

### ISSUE THREAD

**Issue by damao33** [imhanjie/gridea-theme-pure#14]
![image](https://user-images.githubusercontent.com/59427208/81521170-00aec100-9379-11ea-9ef9-f310378cc96b.png)
这是本地渲染的网页预览

**Comment by imhanjie** [comment]
设置里重新选择一下主题的样式风格看看

**Comment by damao33** [comment]
> 设置里重新选择一下主题的样式风格看看

感谢 问题解决了

**Comment by imhanjie** [comment]
这应该是一个 Bug，由于对 Gridea 主题开发不太熟悉，所以目前不知道该怎么解决。
