### ISSUE TITLE
按照安装步骤后，样式与示例站有明显区别

### ISSUE THREAD

**Issue by wxufei** [imhanjie/gridea-theme-pure#2]
[这样式需要自己编写嘛
![image](https://user-images.githubusercontent.com/44740977/72880635-341dff00-3d3a-11ea-8bdb-9933ae03f83e.png)

**Comment by DreamWalkerXZ** [comment]
应该是配置文件错误，在"主题" -> "自定义配置"中设定好并保存也许就能解决问题
