### ISSUE TITLE
搜索功能用不了

### ISSUE THREAD

**Issue by hexotz** [imhanjie/gridea-theme-pure#26]
![截屏_20200731_090636](https://user-images.githubusercontent.com/59991072/88989042-2d181080-d2ca-11ea-8b89-442ae22c8e47.jpg)

**Comment by renbaoshuo** [comment]
我这正常啊，演示：https://baoshuo.blog/search/?q=git

**Comment by imhanjie** [comment]
试下 1.3.0 版本

**Comment by hexotz** [comment]
刚才重装了最新版本，没问题了 谢谢

**Comment by hexotz** [comment]
本地测试没问题，上传后就用不了了
https://blog.ait6.cn/search/index.html?q=gridea

**Comment by twocircles24** [comment]
我也遇到了相同的问题，本地测试OK，上传后无法使用

**Comment by Jiahonzheng** [comment]
pure 主题依赖 result-template.ejs 文件来在前端调用 ejs 实时渲染，而 Gridea 部署时会忽略 ejs 文件的上传，因此搜索一直处于“搜索中”状态。

解决方法：

1.  重命名 `assets/media/gridea-search` 目录下的 `result-template.ejs` 文件为 `result-template.js` 。
2. 修改 `templates/search.ejs` 文件，将 `result-template.ejs` 替换为 `result-template.js` 文件。
