### ISSUE TITLE
代码字体

### ISSUE THREAD

**Issue by wanyt** [imhanjie/gridea-theme-pure#31]
怎么修改代码的字体，谢谢

**Comment by renbaoshuo** [comment]
https://github.com/imhanjie/gridea-theme-pure/blob/master/assets/styles/main.less#L178

请查看此处代码

**Comment by wanyt** [comment]
这个配置只能改变本机预览的字体，不能改变推送到GitHub后的字体。

**Comment by renbaoshuo** [comment]
> 这个配置只能改变本机预览的字体，不能改变推送到GitHub后的字体。

你是不是添加了CDN，请清除缓存后再试，我并没有发现此情况。

**Comment by wanyt** [comment]
> > 这个配置只能改变本机预览的字体，不能改变推送到GitHub后的字体。
> 
> 你是不是添加了CDN，请清除缓存后再试，我并没有发现此情况。

我只做了最简单的GitHubPages的配置，没做cdn或者其他的东西，那我就先不改字体了。
