### ISSUE TITLE
请问如何为网页标题添加超链接

### ISSUE THREAD

**Issue by mzwang828** [imhanjie/gridea-theme-pure#32]
谢谢分享这个很棒的主题，我有一个简单的问题，如何给网站的标题添加超链接？例如作者的示例页面，左上角“imhanjie”只是单纯的文本没有超链接，该如何给这个文本添加链接使得可以通过点击标题返回主页？

抱歉这个问题可能非常基础，但我完全没有前端的知识。。。

**Comment by renbaoshuo** [comment]
你可以参考 https://baoshuo.blog 来修改，或者给我个人主页上的邮箱发邮件，我给你发一份修改过的




------


任宝硕


i@baoshuo.ren







On Thu, Aug 20, 2020 at 11:30 AM +0800, "Maozhen Wang" <notifications@github.com> wrote:















谢谢分享这个很棒的主题，我有一个简单的问题，如何给网站的标题添加超链接？例如作者的示例页面，左上角“imhanjie”只是单纯的文本没有超链接，该如何给这个文本添加链接使得可以通过点击标题返回主页？


抱歉这个问题可能非常基础，但我完全没有前端的知识。。。

**Comment by mzwang828** [comment]
感谢！已经给您发了邮件，因为我实在缺少网页相关的知识，不知该如何下手修改，十分感谢。
