### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Snooper-Y** [imhanjie/gridea-theme-pure#33]
点击左上角用户名，返回首页

**Comment by renbaoshuo** [comment]
请参考 https://github.com/imhanjie/gridea-theme-pure/issues/32

**Comment by sjtuerxu** [comment]
> 请参考 #32

你博客的回到顶部是怎么加的，能不能出个教程或者给个链接

**Comment by renbaoshuo** [comment]
> > 请参考 #32
> 
> 你博客的回到顶部是怎么加的，能不能出个教程或者给个链接

CloudFlare App: `Back To Top Button`
