### ISSUE TITLE
为啥主题在win的电脑上样式会显示错乱

### ISSUE THREAD

**Issue by ShineYangGod** [imhanjie/gridea-theme-pure#36]
主题在win10的谷歌浏览器上显示错乱，在win7的上有的就可以，
![5FF807F34599E6F6E7840D7270AAACCF](https://user-images.githubusercontent.com/19811314/96535498-8b9acc80-12c4-11eb-924f-0cc9f53b29ea.png)

**Comment by renbaoshuo** [comment]
静态资源配置有问题吧

https://baoshuo.blog

我的就没事

**Comment by ShineYangGod** [comment]
已经解决了，谢谢啊

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Baoshuo Ren <notifications@github.com>
发送时间: Tuesday, October 20, 2020 5:08:03 PM
收件人: imhanjie/gridea-theme-pure <gridea-theme-pure@noreply.github.com>
抄送: ShineYang <yangchen_993@outlook.com>; Author <author@noreply.github.com>
主题: Re: [imhanjie/gridea-theme-pure] 为啥主题在win的电脑上样式会显示错乱 (#36)


静态资源配置有问题吧

https://baoshuo.blog

我的就没事

―

**Comment by ShineYangGod** [comment]
主题还会更新吗？主题可以加一些自定义菜单的功能，

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 杨 晨 <yangchen_993@outlook.com>
发送时间: Tuesday, October 20, 2020 5:09:38 PM
收件人: imhanjie/gridea-theme-pure <reply@reply.github.com>
主题: Re: [imhanjie/gridea-theme-pure] 为啥主题在win的电脑上样式会显示错乱 (#36)

已经解决了，谢谢啊

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Baoshuo Ren <notifications@github.com>
发送时间: Tuesday, October 20, 2020 5:08:03 PM
收件人: imhanjie/gridea-theme-pure <gridea-theme-pure@noreply.github.com>
抄送: ShineYang <yangchen_993@outlook.com>; Author <author@noreply.github.com>
主题: Re: [imhanjie/gridea-theme-pure] 为啥主题在win的电脑上样式会显示错乱 (#36)


静态资源配置有问题吧

https://baoshuo.blog

我的就没事

―
