### ISSUE TITLE
英文折行的问题

### ISSUE THREAD

**Issue by LeonWong0609** [imhanjie/gridea-theme-pure#4]
英文单词存在词内折行的问题，需要加上连词符或者直接整个单词折行。

![注意几个行末的单词](https://user-images.githubusercontent.com/58762081/74708152-b543b580-5256-11ea-9f8d-9b3bd22c004f.png)

如上图中 Markdown, Nice 和 CSS 三个词存在不恰当的折行问题。

特别赞的主题，细节十分精致，整体效果简洁而优雅，感谢阁下带来如此美妙的作品。要是能解决这个英文排版的小瑕疵就更接近完美了！:heart:

**Comment by imhanjie** [comment]
新版已经修复。
