### ISSUE TITLE
移植到hexo可以吗？

### ISSUE THREAD

**Issue by lonbaw** [imhanjie/gridea-theme-pure#44]
who can !dalao

**Comment by renbaoshuo** [comment]
我有计划移植，但没时间移植...

**Comment by xiamuguizhi** [comment]
我移植到typecho了 但是  是自用 目前还在本地 还没上线。。

**Comment by lonbaw** [comment]
> 我移植到typecho了 但是 是自用 目前还在本地 还没上线。。

哇哇哇哇哇哇哇，想用hexo，cicd自动更新

**Comment by renbaoshuo** [comment]
移植好了： https://blog.baoshuo.ren/

但是自己改的太多了，内部功能和原版差太多了，暂时不打算发布

**Comment by lonbaw** [comment]
> 移植好了： https://blog.baoshuo.ren/
> 
> 但是自己改的太多了，内部功能和原版差太多了，暂时不打算发布

你这效率也太高了，

**Comment by renbaoshuo** [comment]
> > 移植好了： https://blog.baoshuo.ren/
> > 但是自己改的太多了，内部功能和原版差太多了，暂时不打算发布
> 
> 你这效率也太高了，

直接用 `hexo-renderer-ejs` 和 `hexo-renderer-less` 就能实现 ejs 和 less 的渲染，再稍微改下调用就好了，用不了多少时间

**Comment by lonbaw** [comment]
> > > 移植好了： https://blog.baoshuo.ren/
> > > 但是自己改的太多了，内部功能和原版差太多了，暂时不打算发布
> > 
> > 
> > 你这效率也太高了，
> 
> 直接用 `hexo-renderer-ejs` 和 `hexo-renderer-less` 就能实现 ejs 和 less 的渲染，再稍微改下调用就好了，用不了多少时间

等你打算开源的时候，记得通知我下
，thx

**Comment by renbaoshuo** [comment]
> > > > 移植好了： https://blog.baoshuo.ren/
> > > > 但是自己改的太多了，内部功能和原版差太多了，暂时不打算发布
> > > 
> > > 
> > > 你这效率也太高了，
> > 
> > 
> > 直接用 `hexo-renderer-ejs` 和 `hexo-renderer-less` 就能实现 ejs 和 less 的渲染，再稍微改下调用就好了，用不了多少时间
> 
> 等你打算开源的时候，记得通知我下
> ，thx

我这个可能不符合你的需求，你给我发个邮件，我一会发你一份，你再看看行不行

**Comment by xiamuguizhi** [comment]
@renbaoshuo 太速度了我还在本地 这个是线上测试的  https://nbsir.cn/  增加了pjax~

**Comment by renbaoshuo** [comment]
> @renbaoshuo 太速度了我还在本地 这个是线上测试的 https://nbsir.cn/ 增加了pjax~

Good! 如果你在服务器端输出的时候能把 HTML 压缩一下的话速度会快很多~

**Comment by renbaoshuo** [comment]
已上传 Github ： <https://github.com/renbaoshuo/hexo-theme-pure>

**Comment by lonbaw** [comment]
> 已上传 Github ： https://github.com/renbaoshuo/hexo-theme-pure

It's very nice of you! Thanks, I've tasted it for the first time，the website is https://lonbaw.github.io/

**Comment by Learycn** [comment]
> @renbaoshuo 太速度了我还在本地 这个是线上的 http://xiamuyourenzhang.cn/ 增加了pjax~

大佬能早日上线嘛

**Comment by vanohezy** [comment]
> 我移植到typecho了 但是 是自用 目前还在本地 还没上线。。

求大佬早日上线！🧎‍♀️

**Comment by xiamuguizhi** [comment]
@vanohezy 已发布 [https://github.com/xiamuguizhi/typecho-for-Pure](url)
