### ISSUE TITLE
如何修改代码，实现命令行触发同步？

### ISSUE THREAD

**Issue by lonbaw** [imhanjie/gridea-theme-pure#45]
背景：
想通过CICD自动发布文章，需要一种命令行的可交互方式。类似hexo d -g 这种！
问题：
请问 如何修改代码实现这个功能呢？

**Comment by renbaoshuo** [comment]
这个主题是可以单独拿出来用的（可参考 [`app.js`](https://github.com/imhanjie/gridea-theme-pure/blob/master/app.js) ）。

---

附：[Gridea Mock Render Data](https://github.com/getgridea/mock-json)
