### ISSUE TITLE
一人血书求移植到Typecho

### ISSUE THREAD

**Issue by Learycn** [imhanjie/gridea-theme-pure#46]
这个主题实在太符合我的审美了，太香了。奈何动手实在能力不行，有大佬能移植到Typecho吗！

**Comment by renbaoshuo** [comment]
据我所知， @xiamuguizhi 已经将这款主题移植到了 Typecho 平台上。  
不过也可以看一下我移植的 Hexo 版： [renbaoshuo/hexo-theme-pure](https://github.com/renbaoshuo/hexo-theme-pure) 。

**Comment by xiamuguizhi** [comment]
我过几天 上穿到github吧 typecho版本的~

**Comment by xiamuguizhi** [comment]
@Learycn [https://github.com/xiamuguizhi/typecho-for-Pure](url) 已发布！

**Comment by Learycn** [comment]
> @Learycn [https://github.com/xiamuguizhi/typecho-for-Pure](url) 已发布！

谢谢大佬！！！
