### ISSUE TITLE
如何修改首页的字体？

### ISSUE THREAD

**Issue by tzkyard** [imhanjie/gridea-theme-pure#5]
:smile: 非常感谢分享那么赞的网站主题，但是遇到一个问题就是感觉首页显示的字体有点小，请问这个如何修改呢？
![image](https://user-images.githubusercontent.com/49138808/77058688-bceea980-6a10-11ea-8063-1850111fd164.png)

另外还有一个就是主题对二级标题的渲染好像有问题。
```  
# test1  
## test2   
```
会被渲染成test1test2

**Comment by imhanjie** [comment]
你的那个地方可以使用以下自定义 css 进行修改：
``` csss
.post-abstract * {
    font-size: 13px !important;
}
```
可以自由修改数值调整大小。
