### ISSUE TITLE
移动端NavBar失效

### ISSUE THREAD

**Issue by lonelyuan** [imhanjie/gridea-theme-pure#57]
不会是经典的引入顺序问题吧

![image](https://user-images.githubusercontent.com/44459536/140635689-7a8413a3-1ee6-4dee-8741-a467f54a80d5.png)

看来是没找到按钮元素

**Comment by renbaoshuo** [comment]
fixed in 22eb6b204dc0d5f18936451e5684bf7489cfcdc0
