### ISSUE TITLE
head.ejs中<!-- DEMO JS --> <script src="media/scripts/index.js"></script>

### ISSUE THREAD

**Issue by chenimin** [imhanjie/gridea-theme-pure#6]
<script src="media/scripts/index.js"></script>
应改为

<script src="/media/scripts/index.js"></script>
否则除了首页,别的页面都找不到这个js

**Comment by imhanjie** [comment]
这个你有遇到什么问题吗？这个只是一个样板工程里面的一个 log js，不影响使用的。

**Comment by chenimin** [comment]
我知道不影响使用,但是控制台会有报错.我有点强迫症,哈哈.谢谢大佬的主题,很好看

**Comment by imhanjie** [comment]
那我把去掉吧
