### ISSUE TITLE
页面崩溃

### ISSUE THREAD

**Issue by zhulinyv** [imhanjie/gridea-theme-pure#67]
![image](https://user-images.githubusercontent.com/66541860/183333287-6ed37776-e68c-4048-a763-9537f8d4c88e.png)
如图，同步之后变成了这样。。。

**Comment by renbaoshuo** [comment]
![Snipaste_2022-08-08_11-37-06](https://user-images.githubusercontent.com/47095648/183333488-031a866d-01ca-40cc-be49-f4697915c988.png)


根据图片中的网址无法复现。

**Comment by zhulinyv** [comment]
> 

清空浏览器数据之后可以正常访问了。
