### ISSUE TITLE
是不是要编译啊，style/main.css都404

### ISSUE THREAD

**Issue by jessjava** [imhanjie/gridea-theme-pure#8]
是不是要编译啊，style/main.css都404

**Comment by itczh** [comment]
整个style文件夹为空

**Comment by moyels** [comment]
附议，style文件夹全空，打开网页没有样式。

**Comment by itczh** [comment]
找到原因了，要在自定义设置栏选择一个主题就行了，作者好像没有设置默认值

**Comment by imhanjie** [comment]
默认值是给的了，默认是 black 暗黑色。

**Comment by moyels** [comment]
就是，虽然那边显示了默认值是黑色的，但是保存主题之后直接打开是无效的，需要在那个地方切换一下，比如换成白的再换回黑的，这样打开才能正常显示。
