### ISSUE TITLE
valine评论

### ISSUE THREAD

**Issue by moyels** [imhanjie/gridea-theme-pure#9]
因为Gridea自带的评论Disqus国内不可用，Gitalk着实是不方便，我自己就在pure内加上了valine的评论，[展示页面](https://www.moyel.top/post/pmBa4j8vT/)，您可以看一下，如果可以的话直接加到下个版本的pure中，如果不行的话，哪位同学想要的也可以直接联系我。

**Comment by imhanjie** [comment]
可以方便提个 PR 吗？

**Comment by moyels** [comment]
明天吧，今天太晚了，电脑还在公司。
